# Generated by Django 5.2.7 on 2025-11-15 19:07

from django.db import migrations

def create_default_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    
    roles = [
        {
            'name': 'Super Admin',
            'description': 'Full system access with all permissions',
            'access_level': 100
        },
        {
            'name': 'Admin',
            'description': 'Administrative access with most permissions',
            'access_level': 80
        },
        {
            'name': 'Manager',
            'description': 'Management level access',
            'access_level': 60
        },
        {
            'name': 'Staff',
            'description': 'Staff member with limited permissions',
            'access_level': 40
        },
        {
            'name': 'User',
            'description': 'Basic user access',
            'access_level': 20
        },
        {
            'name': 'Guest',
            'description': 'Guest access with minimal permissions',
            'access_level': 10
        },
    ]
    
    for role_data in roles:
        Role.objects.get_or_create(
            name=role_data['name'],
            defaults={
                'description': role_data['description'],
                'access_level': role_data['access_level']
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
